# for macs with homebrew default install locations
PREFIX = /usr
MANDIR = $(PREFIX)/share/man
RCDIR = /etc/X11
APPLRESDIR = /opt/x11/share/x11/app-defaults

INCDIRS = -I/opt/homebrew/include
LIBDIRS = -L/opt/homebrew/lib

CFLAGS += -Wall -DPREFIX='"$(PREFIX)"' $(INCDIRS)
SYSLIBS = -lcrypt

include common.mf

install: common_install

-include .depend
